/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.pulsar;

import lombok.extern.slf4j.Slf4j;
import org.apache.pulsar.client.api.*;

@Slf4j
public class App {

    public static void main(String[] args) throws PulsarClientException {
        log.info("Creating client");
        PulsarClient pulsarClient = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();

        log.info("Creating producer");
        Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic("test").create();
        log.info("Sending");
        MessageId messageId = producer.send("Hello world!");
        log.info("Sent message {}", messageId);
        producer.close();
        pulsarClient.close();
    }
}
